databases:
  - name: maati-ka-swad-db
    databaseName: maatikaswad
    user: maatikaswad
    plan: free
    ipAllowList: []

services:
  - type: web
    name: maati-ka-swad
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start

  - type: web
    name: maati-ka-swad-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
